# Generated by Django 2.0 on 2017-12-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_AddFieldToBookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='datetimeposted',
            new_name='date_time_posted',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='ispublic',
            new_name='is_public',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(to='bookmark.Tags'),
        ),
    ]
